"use strict";

/**
 * @type Chai.Assert
 */
var assert = require('chai').assert;
var Device = require('../../lib/flow/device');
var Checkpoint = require('../../lib/flow/checkpoint');

describe('Device @small', function () {
    describe('#toJSON', function() {
        it('returns JSON string with device', function() {
            assert.equal(
                JSON.stringify({deviceOptions: {id: 0}, checkpoints: []}),
                new Device({id: 0}).toJSON(),
                "stringified objects don't match"
            )
        })
    })

    describe('#fromJSON', function() {
        it('restores Device generated by #toJSON', function() {
            let device = new Device({id: 'A'})

            assert.deepEqual(device, Device.fromJSON(device.toJSON()));
        })

        it('restores Device with steps generated by #toJSON', function() {
            let device = new Device({id: 'A'}).addCheckpoints([new Checkpoint(0, 'name')])

            assert.deepEqual(device, Device.fromJSON(device.toJSON()));
        })
    })

})
